; Script generated by the Antigravity Coding Assistant.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Academic Paper Downloader"
#define MyAppVersion "3.0.1.0"
#define MyAppPublisher "Yazid YOUCEF"
#define MyAppURL "https://github.com/dzmarkets/Academic-Paper-Downloader"
#define MyAppExeName "paper.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the Inno Setup IDE.)
AppId={{D8F8D69A-B2CE-4E9D-BC44-48E06A57D0D4}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={userprograms}\{#MyAppName}
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=AcademicPaperDownloader_Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
AppMutex=AcademicPaperDownloaderMutex
DisableFinishedPage=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "dist\paper\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; AfterInstall: LogInstallFile
; Source: "app_icon.png"; DestDir: "{app}"; Flags: ignoreversion
; Note: Don't pack the downloaded folder structure since the app creates it dynamically on startup!

[Icons]
Name: "{userprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"
Name: "{userdesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"

[Run]
Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"; Flags: nowait

[Code]
var
  DetailMemo: TNewMemo;

procedure InitializeWizard;
begin
  // Create detail memo on the Installing page
  DetailMemo := TNewMemo.Create(WizardForm);
  DetailMemo.Parent := WizardForm.InstallingPage;
  DetailMemo.Left := WizardForm.ProgressGauge.Left;
  DetailMemo.Top := WizardForm.ProgressGauge.Top + WizardForm.ProgressGauge.Height + ScaleY(15);
  DetailMemo.Width := WizardForm.ProgressGauge.Width;
  DetailMemo.Height := ScaleY(120);
  DetailMemo.ScrollBars := ssVertical;
  DetailMemo.ReadOnly := True;
  DetailMemo.Color := clWindow;
  DetailMemo.Font.Name := 'Segoe UI';
  DetailMemo.Font.Size := 8;
end;

procedure LogInstallFile;
begin
  if DetailMemo <> nil then
  begin
    DetailMemo.Lines.Add('Extracting: ' + ExtractFileName(CurrentFilename));
    // Scroll to the bottom of the memo
    SendMessage(DetailMemo.Handle, $0115, 7, 0); // WM_VSCROLL, SB_BOTTOM
  end;
end;
